#! /bin/bash

sudo apt-get install -y htop

PWD="`pwd`/config-packages"

mkdir -p ~/.config/htop
[[ -f ~/.config/htop/htoprc ]] && rm ~/.config/htop/htoprc
[[ ! -h  ~/.config/htop/htoprc ]] && ln -s $PWD/htop_files/htoprc ~/.config/htop/htoprc

if [[ $ONEUSER == 1 ]]
then
	sudo mkdir -p /root/.config/htop
	sudo [ -f /root/.config/htop/htoprc ] && sudo rm /root/.config/htop/htoprc
	sudo [ ! -h /root/.config/htop/htoprc ] && sudo ln -s $PWD/htop_files/htoprc /root/.config/htop/htoprc
fi