#! /bin/bash

sudo apt-get install python python-pip python2.7 python3 python3-pip

PWD="`pwd`/config-packages"

#create new env
mkdir ~/.venvs
python3 -m venv ~/.venvs/python-3
. ~/.venvs/python-3/bin/activate

#install common pip
pip install -r $PWD/python_files/requirement.txt

if [[ $PIPOPTIONAL == 1 ]]
then
  pip install -r $PWD/python_files/optional.txt
fi

if [[ $PIPUNISTELLAR == 1 ]]
then
  pip install -r $PWD/python_files/unistellar.txt
fi