#! /bin/bash

sudo apt-get install python
sudo apt-get install python-pip
sudo apt-get install python2.7
sudo apt-get install python3
sudo apt-get install python3-pip

PWD="`pwd`/config-packages"

#create new env
mkdir ~/.venvs
python3 -m venv ~/.venvs/python-3
. ~/.venvs/python-3/bin/activate

#install common pip
PKGS=`cat $PWD/python_files/requirement.txt`
for i in $PKGS
do
    n=`echo $i | sed -n -e 's/==.*//p'`
    pip install $n
done

if [[ $PIPOPTIONAL == 1 ]]
then
    PKGS=`cat $PWD/python_files/option.txt`
    for i in $PKGS
    do
        n=`echo $i | sed -n -e 's/==.*//p'`
        pip install $n
    done
fi

if [[ $PIPUNISTELLAR == 1 ]]
then
    PKGS=`cat $PWD/python_files/unistellar.txt`
    for i in $PKGS
    do
        n=`echo $i | sed -n -e 's/==.*//p'`
        pip install $n
    done
fi
