export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
export CLICOLOR=1
#export LSCOLORS=GxFxCxDxBxegedabagaced
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export PS1="\[\e[1;32m\]\u\e[0m@\[\e[1;31m\]\w\e[0m $ "
alias ls='ls -G'
source /Users/alexis/.bazel/bin/bazel-complete.bash

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

source ~/.bashrc

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/alexis/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/alexis/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/alexis/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/alexis/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

